# Generated by Django 5.1.2 on 2024-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('button_text', models.CharField(max_length=100)),
            ],
        ),
    ]
