# Generated by Django 5.1.2 on 2024-11-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_agent_agentapplication_blog_blogcategory_contactinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=15)),
                ('image', models.ImageField(default='profile.png', upload_to='team/')),
                ('bio', models.TextField()),
                ('twitter_url', models.CharField(blank=True, max_length=55, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=55, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=55, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
