# Generated by Django 5.1.2 on 2024-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
