# Generated by Django 5.1.2 on 2024-12-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0007_propertyimage_delete_propertyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('land', 'Land'), ('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('listings', 'Listings')], default='Listings', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
