# Generated by Django 5.1.2 on 2024-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0008_property_category_property_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('land', 'Land'), ('apartment', 'Apartment'), ('home', 'Home'), ('mall', 'Mall')], max_length=20, null=True),
        ),
    ]
