# Generated by Django 5.1.2 on 2024-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
